#!/usr/bin/env node

var lib = require('allexlib'),
  BasicProgram = require('allex_basicprogramsdklib')(lib),
  Node = require('allex_nodehelpersserverruntimelib')(lib),
  clone = require('../src/ws/websuites/clonedeployment')(lib, Node);

var p = new BasicProgram(__dirname);
p.program
  .usage('[options] <project> <gitpath> <name>')
  .option ('-f, --force', 'Force clone');

p.go();

if (p.program.args.length < 3) {
  Node.error('Insufficient arguments');
  p.showHelp();
  process.exit();
}

clone(p.program.args[1], {
  force : !!p.program.force,
  project: p.program.args[0],
  name : p.program.args[2]
}).done (
  Node.info.bind(Node),
  Node.error.bind(Node)
);
