#!/usr/bin/env node
var Fs = require('fs'),
  Path = require('path'),
  file = process.argv[2];
  relative = process.argv[3];

file = Fs.realpathSync(file);
if (!relative) {
  console.log(file);
  process.exit(0);
}

console.log(Fs.realpathSync(Path.resolve(Path.dirname(file), relative)));
