#!/usr/bin/env node
var lib = require('allexlib'),
  BasicProgram = require('allex_basicprogramsdklib')(lib),
  Grunter = require('allex_grunthelperssdklib')(lib);

var p = new BasicProgram(__dirname);
p.program.usage('Run this program in order to build a webapp component');
p.go();

Grunter.goforGrunt(require('../src/webalizer/grunt_web_component.js'));
