#!/usr/bin/env node

var lib = require('allexlib'),
  BasicProgram = require('allex_basicprogramsdklib')(lib),
  Node = require('allex_nodehelpersserverruntimelib')(lib),
  clone = require('../src/ws/modules/clone')(lib, Node);


var p = new BasicProgram(__dirname);
p.program
  .option ('-f, --force', 'Force clone')
  .usage('<module_or_gitpath> [options]');
p.go();

if (!p.program.args.length) {
  Node.error('Insufficient arguments');
  p.showHelp();
  process.exit();
}

clone(p.program.args[0], {
  force : !!p.program.force
}).done (
  Node.info.bind(Node),
  Node.error.bind(Node)
);
