#!/usr/bin/env node

var lib = require('allexlib'),
  BasicProgram = require('allex_basicprogramsdklib')(lib),
  Node = require('allex_nodehelpersserverruntimelib')(lib),
  clone = require('../src/ws/websuites/clonetosuite')(lib, Node);

var p = new BasicProgram(__dirname);
p.program
  .usage('[options] <project> <gitpath_or_name>')
  .option ('-f, --force', 'Force clone');

p.go();

if (p.program.args.length < 2) {
  Node.error('Insufficient arguments');
  p.showHelp();
  process.exit();
}

clone(p.program.args[1], {
  force : !!p.program.force,
  project: p.program.args[0]
}).done (
  Node.info.bind(Node),
  Node.error.bind(Node)
);

